# Generated by Django 3.2.23 on 2024-01-29 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
        ('wallitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallitem',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
